# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19a77b4aef9f1b69647e1d962c0527b251ed0e0bfe35e597462bf545368d65b8c7b67605aad026523d209da7707e667a5711ae7eed1aab6080f7acc131d769c

test:
  secret_key_base: fe5a5fa7d67cab9e7c7e410595a1588c2a0f6fe853cc61c1581544a0a157194324bc418536b7a7d7c4c5090f664ad2f1d166977f3df618623018dc85cece683d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
